server:
  port: 7777
  tomcat:
    max-http-form-post-size: 1000MB


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/pcb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    filters: stat,wall,log4j
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1000MB
      max-request-size: 1000MB
  freemarker:
    checkTemplateLocation: false
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/static/
    suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000s
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 2

mybatis:
  type-aliases-package: zjnu.huawei.pcb.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    zjnu.huawei.pcb.mapper: debug
#  file:
#    name: D:/navy/log/navy_error_log.log

minio:
  endpoint: http://localhost:9000
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: pcb

# 应用自定义属性
application:
  jwt:
    # 加密秘钥
    secret: ADB8E3D5838A0AE8E274014928CE2CEE
    # token有效时长，60 * 4小时，单位分钟
    expire: 240
    #小程序ID
    appKey: dingdwxevgtgyuc676mb
    #小程序密钥
    appSecret: 7BEGSoA7Xk2xXRCxDR0dxYvtymwcWHJ6oBcsiNNyTe3HcMPJsNqg19DdKcXQTqaV

  # 用于文档导入导出
  res:
    disk: D

